

###
# ingest one file
GET http://localhost:8000/api/ingest?file=uganda
Accept: application/json

###
# ingest all files
GET http://localhost:8000/api/ingest/all
Accept: application/json

###
# Get all Universities
GET http://localhost:8000/api/universities
Accept: application/json

###
# Get all Universities with filters
GET http://localhost:8000/api/universities?country=burundi
Accept: application/json

###
# Get a University by ID
GET http://localhost:8000/api/universities/63bf99ef0f470d3923c7ca6f
Accept: application/json

###
# Create a new University
POST http://localhost:8000/api/universities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzJlZjJmNjAzYjRjNDE1MDk0MzEyYyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNDA1MTI1NCwiZXhwIjoxNzI0MDU0ODU0fQ.d8R4oRCmmrvTBHqC2olom6mseR0Ce-B-enNYjMBl2dI
Content-Type: application/json
Accept: application/json

{
  "country": "United Kingdom",
  "alpha_two_code": "GB",
  "domains": [
    "myport.ac.uk",
    "myport.port.ac.uk"
  ],
  "state_province": null,
  "web_pages": [
    "https://myport.port.ac.uk"
  ],
  "name": "University of Portsmouth",
  "continent": "Europe",
  "established_year": 1992,
  "student_population": 25000,
  "programs_offered": [
    "Computer Science",
    "Business Administration",
    "Mechanical Engineering"
  ],
  "contact_info": {
    "address": "Winston Churchill Avenue, Portsmouth, PO1 2UP, UK",
    "phone": "+44 23 9284 8484",
    "email": "info@port.ac.uk"
  },
  "latitude": 50.7984,
  "longitude": -1.0974
}

###
# Update a University
PUT http://localhost:8000/api/universities/66bf99ef0f470d3923c7ca7f
Content-Type: application/json
Accept: application/json

{
  "student_population": 26000,
  "ranking": {
    "world": 450,
    "national": 25
  }
}

###
# Delete a University
DELETE http://localhost:8000/api/universities/66c10d8fa7d8a9d2ba0973f7
Accept: application/json

###
# Register a new User or Admin
POST http://localhost:8000/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "admin@example.com",
  "password": "admin_password",
  "role": "admin"
}

###
# Login as User or Admin
POST http://localhost:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@example.com",
  "password": "admin_password"
}

###
# Approve a User (Admin only)
PUT http://localhost:8000/api/auth/approve/66c1f05fc1b9c4add56ef270
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzEzM2FhYTg0ZGVmZjA0OGI4ODU1MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzk4NjAzMSwiZXhwIjoxNzIzOTg5NjMxfQ.7wTMvwtb3aQgZgJyqoUdFsrP-4k1WYsKxSobzMNg964
Accept: application/json

###
# Get all Users (Admin only)
GET http://localhost:8000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzEzM2FhYTg0ZGVmZjA0OGI4ODU1MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzkzNzg1MSwiZXhwIjoxNzIzOTQxNDUxfQ.dXXQb32G8qrh4P1mQNbS2lTDBWlG5h3S-MQmC9JnpAs
Accept: application/json

###
# Update User or Admin's own profile
PUT http://localhost:8000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzEzM2FhYTg0ZGVmZjA0OGI4ODU1MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzkzNzc1NywiZXhwIjoxNzIzOTQxMzU3fQ.FCTYz4XzS_rU1XysbCpwN5MszYCqdTxmBJ_srKtGhv8
Content-Type: application/json
Accept: application/json

{
  "email": "updatedadmin@example.com",
  "password": "updateadmin_password"
}

###
# Delete User or Admin's own profile
DELETE http://localhost:8000/api/auth/me
Authorization: Bearer <your_user_or_admin_jwt_token>
Accept: application/json

###
# Shared Action accessible by both Users and Admins
GET http://localhost:8000/api/auth/shared-action
Authorization: Bearer <your_user_or_admin_jwt_token>
Accept: application/json
