version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network

  express-api:
    build: .
    ports:
      - 8000:8000
    networks:
      - mongo-network
  
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    networks:
      - mongo-network
   
volumes:
  mongo-volume:
    driver: local

networks:
  mongo-network:
    driver: bridge
